id: P008079
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG16596
  title: སྨན་རིས་གསལ་བའི་མེ་ལོང་།
  author: ''
  volumes:
    cade92fb714d468d853adbf144c6e4f3:
      image_group_id: I4PD4439
      title: ''
      volume_number: 1
      total_pages: 874
    acbc02e9b58f4daba3d14e25cc2f3349:
      image_group_id: I4PD4440
      title: ''
      volume_number: 2
      total_pages: 700
    08a9d69380464bf898243266460180d7:
      image_group_id: I4PD4441
      title: ''
      volume_number: 3
      total_pages: 314
ebook_metadata:
  title: སྨན་རིས་གསལ་བའི་མེ་ལོང་།
  author: ''
  sku: P008079
  cover: cover.jpg
  layers:
  - pagination
