id: I997C29B5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T13:56:01+00:00'
last_modified: '2022-06-09T04:08:13.120625+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG16596
  title: སྨན་རིས་གསལ་བའི་མེ་ལོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    59A5:
      image_group_id: I4PD4439
      title: Volume 1 of sman ris gsal ba'i me long /
      total_pages: 874
      order: 1
      base_file: 59A5.txt
    '9585':
      image_group_id: I4PD4440
      title: Volume 2 of sman ris gsal ba'i me long /
      total_pages: 700
      order: 2
      base_file: 9585.txt
    41CE:
      image_group_id: I4PD4441
      title: Volume 3 of sman ris gsal ba'i me long /
      total_pages: 314
      order: 3
      base_file: 41CE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
